# Generated by Django 4.1.6 on 2023-02-07 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_id", models.PositiveIntegerField()),
                ("player_name", models.CharField(max_length=128)),
                ("age", models.PositiveIntegerField()),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Batsmen", "BATSMAN"),
                            ("Bowler", "BOWLER"),
                            ("All Rounder", "ALL ROUNDER"),
                        ],
                        max_length=32,
                    ),
                ),
                ("nationality", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Venues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("venue_id", models.PositiveIntegerField()),
                ("stadium_name", models.CharField(max_length=32)),
                ("location", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Matches",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_id", models.PositiveIntegerField()),
                ("opponent_name", models.CharField(max_length=128)),
                ("match_date", models.DateField()),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("Win", "WIN"),
                            ("Loss", "LOSS"),
                            ("Draw", "DRAW"),
                            ("No Result", "NO RESULT"),
                        ],
                        default="no_result",
                        max_length=32,
                    ),
                ),
                (
                    "match_venue",
                    models.ForeignKey(
                        default="venue name",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venues",
                        to="teamapp.venues",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bowler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bowler_id", models.PositiveIntegerField()),
                ("real_name", models.CharField(default="c", max_length=128)),
                ("no_matches", models.PositiveIntegerField(default=0)),
                ("total_runs", models.PositiveIntegerField(default=0)),
                ("total_balls", models.PositiveIntegerField(default=0)),
                ("total_wickets", models.PositiveIntegerField(default=0)),
                ("average", models.FloatField(default=0.0)),
                ("economy", models.FloatField(default=0.0)),
                ("fourhauls", models.PositiveIntegerField(default=0)),
                ("fivehauls", models.PositiveIntegerField(default=0)),
                (
                    "bowler_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bowlername",
                        to="teamapp.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Batsman",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batsman_id", models.PositiveIntegerField()),
                ("real_name", models.CharField(default="c", max_length=128)),
                ("no_matches", models.PositiveIntegerField(default=0)),
                ("total_runs", models.PositiveIntegerField(default=0)),
                ("total_balls", models.PositiveIntegerField(default=0)),
                ("average", models.FloatField(default=0.0)),
                ("strike_rate", models.FloatField(default=0.0)),
                ("fifties", models.PositiveIntegerField(default=0)),
                ("hundreds", models.PositiveIntegerField(default=0)),
                (
                    "batsman_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batsmanname",
                        to="teamapp.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Auction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auction_id", models.PositiveIntegerField()),
                ("bought_price", models.PositiveIntegerField(default=0)),
                ("sold_price", models.PositiveIntegerField(default=0)),
                ("player_status", models.CharField(default="Status", max_length=128)),
                (
                    "player_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auction_player_name",
                        to="teamapp.player",
                    ),
                ),
            ],
        ),
    ]
